### ISSUE TITLE
Imagenes de productos

### ISSUE THREAD

**Issue by NicoGonzalez94** [arieldg39/eStore-app#21]
## Proceso

1. Ingrese a la app.
2. Me loguee con un usuario.

## Resultado esperado

• Que todos los productos tengan su imagen correspondiente en condiciones.

## Resultado actual

• Las imágenes de los productos no cargan correctamente.

## Captura

![file (1)](https://github.com/arieldg39/eStore-app/assets/166792979/d03ce545-e9dd-4161-8ff4-4ad1cbfc792d)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by arieldg39** [comment]
se corrigio el problema de las imagenes, las mismas se cargar correctamente, el problema surgio el guardar mal el path de la misma en la BD. 
Link de la App corregida : https://expo.dev/preview/update?message=Correcciones&updateRuntimeVersion=1.0.0&createdAt=2024-05-21T12%3A18%3A49.735Z&slug=exp&projectId=ef957c1e-fc36-4e42-91e5-8f3dcb3adba7&group=a72a2c0d-1b35-4d00-be4e-0c0a07a0a64f
